name: CI-pr

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CARGO_INCREMENTAL: 0

jobs:
  build_and_check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, clippy
      - name: Compile
        run: cargo test --no-run
      - name: Test
        run: cargo test -- --nocapture --quiet
      - name: Clippy
        run: cargo clippy
      - name: Check Formatting
        run: cargo fmt -- --check
