name: Publish

on: workflow_dispatch

env:
  CARGO_INCREMENTAL: 0

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, clippy
      - name: Get current version
        id: version
        run: .github/workflows/print-version.sh
      - name: Compile Tests
        run: cargo test --no-run
      - name: Test
        run: cargo test -- --nocapture --quiet
      - name: Clippy
        run: cargo clippy
      - name: Check Formatting
        run: cargo fmt -- --check
      - name: Build Release
        run: cargo build --release --all-features
      - name: Login to crates.io
        run: cargo login ${{ secrets.CRATES_IO_TOKEN }}
      - name: Publish
        run: cargo publish
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: v${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
